mqtt:
  server: 192.168.1.2
  port: 1883

whirlpool:
  username: xxx@xxx.xx
  password: xxxx
  polling: 30
  channels: [
              "XCat_WifiStatusIspCheck",
              "XCat_RemoteSetRemoteControlEnable",
              "XCat_WifiSetPublishApplianceState",
              "XCat_WifiSetIspAuthorized",
              "Sys_AlertStatusNotification",
              "Sys_DisplaySetLanguage",
              "Sys_DisplaySetTempUnits",
              "Sys_DisplaySetEnable24Hour",
              "Sys_OperationSetControlLock",
              "Sys_OperationSetKeyPressToneVolume",
              "Sys_OperationSetAlertToneVolume",
              "Sys_OperationSetSabbathModeEnabled",
              "OvenUpperCavity_OpStatusCookTimeState",
              "OvenUpperCavity_OpStatusDoorOpen",
              "OvenUpperCavity_OpStatusState",
              "OvenUpperCavity_OpStatusCleanOven",
              "OvenUpperCavity_AlertStatusMeatProbePluggedIn",
              "OvenUpperCavity_DisplaySetLightOn",
              "OvenUpperCavity_OpSetCookTimeCompleteAction",
              "OvenUpperCavity_OpSetOperations",
              "OvenUpperCavity_OpSetSabbathModeActive",
              "OvenUpperCavity_CycleSetDoneness",
              "OvenUpperCavity_CycleSetPreheatOn",
              "OvenUpperCavity_CycleSetBrowning",
              "OvenUpperCavity_CycleSetBroilLevel",
              "OvenUpperCavity_CycleSetCommonMode",
              "OvenUpperCavity_CycleSetFrozenBakeFood",
              "OvenUpperCavity_CycleSetFrozenCustomFood",
              "OvenUpperCavity_CycleSetMultiRackFood",
              "OvenUpperCavity_CycleSetBreadProof",
              "OvenUpperCavity_CycleSetCleanOvenMode",
              "KitchenTimer01_StatusState",
              "KitchenTimer01_SetOperations",
              "Relational_EnvelopeAction",
              "XCat_PersistentInfoVersion",
              "XCat_PersistentInfoSaid",
              "XCat_PersistentInfoMacAddress",
              "XCat_WifiStatusRssiAntennaDiversity",
              "XCat_OdometerStatusRunningHours",
              "XCat_OdometerStatusTotalHours",
              "XCat_OdometerStatusCycleCount",
              "XCat_ApplianceInfoSetModelNumber",
              "XCat_ApplianceInfoSetSerialNumber",
              "XCat_DateTimeSetDateTimeSet",
              "XCat_WifiSetIspFirmwareDescriptionUrl",
              "Sys_AlertStatusCustomerFaultCode",
              "Sys_DisplaySetBrightnessPercent",
              "Sys_OperationSetMaxCurrentLimit",
              "OvenUpperCavity_TimeStatusCookTimeRemaining",
              "OvenUpperCavity_TimeStatusCycleTimeElapsed",
              "OvenUpperCavity_TimeStatusDelayTimeRemaining",
              "OvenUpperCavity_DisplStatusDisplayTemp",
              "OvenUpperCavity_DisplStatusMeatProbeDisplayTemp",
              "OvenUpperCavity_OpStatusRawTemp",
              "OvenUpperCavity_CycleStatusOdometer",
              "OvenUpperCavity_TimeSetCookTimeSet",
              "OvenUpperCavity_TimeSetDelayTime",
              "OvenUpperCavity_DisplaySetZonedMessage",
              "OvenUpperCavity_CycleSetTargetTemp",
              "OvenUpperCavity_CycleSetMeatProbeTargetTemp",
              "OvenUpperCavity_CycleSetExtraCookingTime",
              "OvenUpperCavity_CycleSetDonenessAdjust",
              "OvenUpperCavity_CulinaryCtrSetId",
              "OvenUpperCavity_CulinaryCtrSetQuantity",
              "OvenUpperCavity_CustomCycleSetId",
              "OvenUpperCavity_CustomCycleSetStep",
              "KitchenTimer01_StatusTimeRemaining",
              "KitchenTimer01_SetTimeSet",
              "Relational_CycleMyCreation",
              "Relational_CycleRecentCycles",
              "ProjectReleaseNumber",
              "ISPStep",
              "Generic_ApplianceVersionNumber",
              "Generic_ISPBundleAttribute"
]